---
- name: Create service directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ntp__user }}"
    group: "{{ ntp__group }}"
    mode: "{{ ntp__dir_mode }}"
  loop: "{{ ntp__directories }}"

- name: "Create the configuration file"
  template:
    src: etc/ntp.conf.j2
    dest: "{{ ntp__conf_file }}"
    owner: "{{ ntp__user }}"
    group: "{{ ntp__group }}"
    mode: "{{ ntp__file_mode }}"
  notify: Restart ntp service
...
