---
- block:
    - name: Create a daemon group
      group:
        name: "{{ ntp__group }}"
        system: true
      notify: Restart ntp service

    - name: Create a daemon user
      user:
        name: "{{ ntp__user }}"
        group: "{{ ntp__group }}"
        system: true
        createhome: false
        comment: "{{ ntp__description }}"
      notify: Restart ntp service
  when: ntp__user != "root"

- name: Install service packages
  yum:
    name: "{{ ntp__packages }}"
    state: present
    update_cache: true
  notify: Restart ntp service

- name: Create service directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ntp__user }}"
    group: "{{ ntp__group }}"
    mode: "{{ ntp__dir_mode }}"
  loop: "{{ ntp__directories }}"
  notify: Restart ntp service

- name: Create the system environment file
  template:
    src: etc/sysconfig/ntpd.j2
    dest: "{{ ntp__sysconfig_file }}"
    mode: "{{ ntp__file_mode }}"
  register: ntp__system_configuration
  notify:
    - Systemd daemon reload
    - Restart ntp service
...
