---
- name: Remove the system environment file
  file:
    path: "{{ ntp__sysconfig_file }}"
    state: absent

- name: Remove service directories
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ ntp__directories }}"

- name: Uninstall service packages
  yum:
    name: "{{ ntp__packages }}"
    state: absent

- block:
    - name: Delete the daemon user
      user:
        name: "{{ ntp__user }}"
        state: absent
        remove: true

    - name: Delete the daemon group
      group:
        name: "{{ ntp__group }}"
        state: absent

  when: ntp__user != "root"
...
