---
- name: Remove service directories
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ ntp__directories }}"

- name: Uninstall service packages
  yum:
    name: "{{ ntp__packages }}"
    state: absent
...
