---
- name: Systemd daemon reload
  systemd:
    name: "{{ ntp__service_name }}"
    daemon_reload: true
  when:
    - not ntp__service_started.changed | default(false)

- name: Restart ntp service
  systemd:
    name: "{{ ntp__service_name }}"
    state: restarted
  register: ntp__service_restarted
  when:
    - not ntp__service_started.changed | default(false)
    - not ntp__service_restarted.changed | default(false)
...
